volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend: 
    image: feystral/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: feystral/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
  gateway:
    image: feystral/foodgram_gateway:latest
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - frontend